[project]
name = "09-serverless"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "keras-image-helper>=0.0.2",
    "onnxruntime>=1.23.2",
]
